import { get } from "lodash";
import type { NextPage } from "next";
import { Box } from "@chakra-ui/react";
import { getDataFromTree } from "@apollo/client/react/ssr";

import Head from "next/head";
import WithApollo from "../lib/Apollo";
import { GetUsersQuery, useGetUsersQuery } from "../generated";

const Home: NextPage = (props) => {
  const { data } = useGetUsersQuery();
  const users = get(data, "users") as GetUsersQuery["users"];

  return (
    <div>
      <Head>
        <title>Taskaider V3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default WithApollo(Home, { getDataFromTree });
